theme: "hugo-PaperMod"
baseURL: http://tato-lu.netlify.app/
paginate: 5
languageCode: en-us
title: Tato Lu

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
    main:
      - identifier: about
        name: about
        url: /about/
        weight: 10
      - identifier: resume
        name: resume
        url: /resume/
        weight: 10

params:
  homeInfoParams:
    Title: "Portfolio"
    Content: >
      **Tato** is an economist and data enthusiast currently working in consulting. Experienced in solving analytical problems at the intersection of business, economics, and law. 
      
      >
      - **Technical Skills:** R, Python, SQL, Excel, and Tableau.
      
      >
      - **Interests:** Data Visualization, Machine Learning (Clustering, Classification, Regression, NLP), Survey Design"
      
  socialIcons:
    - name: github
      url: "https://github.com/tomatatoro"
    - name: linkedin
      url: "https://linkedin.com/in/tatolu/"
    - name: email
      url: "tatolu818@gmail.com"