theme: "hugo-PaperMod"
baseURL: http://tato-lu.netlify.app/
paginate: 5
languageCode: en-us
title: Tato Lu

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  homeInfoParams:
    Title: "Tato"
    Content: >
      Test
      - **test**
    
  socialIcons:
    - name: github
      url: "https://github.com/tomatatoro"
      
      
  menu:
    main:
      - identifier: about
        name: about
        url: /about/
        weight: 10