theme: "hugo-PaperMod"
baseURL: http://tato-lu.netlify.app/
paginate: 5
languageCode: en-us
title: Tato Lu

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
    main:
      - identifier: about
        name: about
        url: /about/
        weight: 10
      - identifier: resume
        name: resume
        url: /resume/
        weight: 10

params:
  homeInfoParams:
    Title: "Tato's Portfolio Site"
    Content: >  
      Welcome to my portfolio! I'm a coder, artist, and data enthusiast, and I'm passionate about crafting stories. I have four years of experience in economic consulting, where I solve complex, analytical problems at the intersection of business, economics, and law. 
      
      >
      - **Programs:** R, SQL, Excel, SAS, and Tableau.
      
      >
      - **Skills:** Regression Modeling, Clustering, Natural Language Processing, Data Visualization
      
  socialIcons:
    - name: github
      url: "https://github.com/tomatatoro"
    - name: linkedin
      url: "https://linkedin.com/in/tatolu/"
    - name: email
      url: "tatolu818@gmail.com"